//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_leave_settings
    {
        public int LeaveId { get; set; }
        public string LeaveCode { get; set; }
        public string LeaveName { get; set; }
        public int Days { get; set; }
        public string Remarks { get; set; }
        public string LeaveDescription { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_employee_profile eng_employee_profile1 { get; set; }
        public virtual eng_leave_master eng_leave_master { get; set; }
    }
}
