//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_holiday
    {
        public int HolidayId { get; set; }
        public string HolidayCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> Country { get; set; }
        public string Day { get; set; }
    
        public virtual countryMaster countryMaster { get; set; }
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_employee_profile eng_employee_profile1 { get; set; }
    }
}
