//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_users()
        {
            this.eng_claim = new HashSet<eng_claim>();
            this.eng_claim1 = new HashSet<eng_claim>();
            this.eng_role = new HashSet<eng_role>();
            this.eng_role1 = new HashSet<eng_role>();
            this.eng_safety_master = new HashSet<eng_safety_master>();
            this.eng_time_entry = new HashSet<eng_time_entry>();
            this.eng_time_entry_submit = new HashSet<eng_time_entry_submit>();
            this.eng_time_entry_submit1 = new HashSet<eng_time_entry_submit>();
            this.eng_time_entry_submit2 = new HashSet<eng_time_entry_submit>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string UID { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_claim> eng_claim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_claim> eng_claim1 { get; set; }
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_employee_profile eng_employee_profile1 { get; set; }
        public virtual eng_employee_profile eng_employee_profile2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_role> eng_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_role> eng_role1 { get; set; }
        public virtual eng_role eng_role2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_safety_master> eng_safety_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_time_entry> eng_time_entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_time_entry_submit> eng_time_entry_submit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_time_entry_submit> eng_time_entry_submit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_time_entry_submit> eng_time_entry_submit2 { get; set; }
        public virtual eng_usergroup eng_usergroup { get; set; }
    }
}
