//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_time_entry_submit
    {
        public int TimeEntryId { get; set; }
        public string TimeEntryCode { get; set; }
        public Nullable<int> ProjectName { get; set; }
        public Nullable<System.TimeSpan> WorkStartTime { get; set; }
        public Nullable<System.TimeSpan> WorkEndTime { get; set; }
        public Nullable<int> Leave { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string ApprovalRemarks { get; set; }
        public string RejectedRemarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> ReportManager { get; set; }
    
        public virtual eng_project eng_project { get; set; }
        public virtual eng_users eng_users { get; set; }
        public virtual eng_time_entry_submit eng_time_entry_submit1 { get; set; }
        public virtual eng_time_entry_submit eng_time_entry_submit2 { get; set; }
        public virtual eng_users eng_users1 { get; set; }
        public virtual eng_users eng_users2 { get; set; }
    }
}
